# Site settings
title: Coder Ken
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ramblings from a web and mobile developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.coderken.com" # the base hostname & protocol for your site
twitter_username: krcourville
github_username: krcourville

# Build settings
markdown: kramdown
page.ishome: false

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

kramdown:
  toc_levels: 2..2
